import { CryptoTableCategories } from '../types/crytoTableTypes';
import BTC from 'shared/assets/coins/BTC.png';
export enum CryptoTableCategory {
  ALL,
  COINS,
  ERC20,
  TRC20,
}
export const coinCategories: CryptoTableCategories[] = [
  {
    type: CryptoTableCategory.ALL,
    title: 'All coins',
    elements: [
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
    ],
  },
  {
    type: CryptoTableCategory.COINS,
    title: 'Coins',
    elements: [
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
    ],
  },
  {
    type: CryptoTableCategory.ERC20,
    title: 'ERC20',
    elements: [
      {
        name: 'Bitcoin1 (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin2 (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
    ],
  },
  {
    type: CryptoTableCategory.TRC20,
    title: 'TRC20',
    elements: [
      {
        name: 'Bitcoin3 (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin4 (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
      {
        name: 'Bitcoin (BTC)',
        img: BTC,
        price: 23179.04,
        send: true,
        exchange: true,
        stake: 1,
      },
    ],
  },
];
